/**
 * process是node.js的一个对象，
 * 它代表当前Node.js进程。通过process对象可以拿到许多有用信息
 * */
//进程号
console.log(global.process.pid);
/***利用process来进行监听一些事件
 * 退出程序时，执行某个方法
 *
 * @type {NodeJS.Process}
 */
var process=global.process;
/***
 * 如果我们想要在下一次事件响应中执行代码，
 * 可以调用process.nextTick()：
 */
process.nextTick(function () {
    console.log("启动新的事件！");
});
process.on("exit",function () {
    console.log("退出程序");
});
function  hh() {
    console.log("调用hh方法");
}
hh();
//这里面包含了很多进程有用的信息：包括版本号、安装路径信息等
//console.log(global.process);
/***
 * process {
  title: 'F:\\node\\node.exe',
  version: 'v10.16.3',
  versions:
   { http_parser: '2.8.0',
     node: '10.16.3',
     v8: '6.8.275.32-node.54',
     uv: '1.28.0',
     zlib: '1.2.11',
     brotli: '1.0.7',
     ares: '1.15.0',
     modules: '64',
     nghttp2: '1.39.2',
     napi: '4',
     openssl: '1.1.1c',
     icu: '64.2',
     unicode: '12.1',
     cldr: '35.1',
     tz: '2019a' },
  arch: 'x64',
  platform: 'win32',
  release:
   { name: 'node',
     lts: 'Dubnium',
     sourceUrl:
      'https://nodejs.org/download/release/v10.16.3/node-v10.16.3.tar.gz',
     headersUrl:
      'https://nodejs.org/download/release/v10.16.3/node-v10.16.3-headers.tar.gz',
     libUrl:
      'https://nodejs.org/download/release/v10.16.3/win-x64/node.lib' },
  argv:
   [ 'F:\\node\\node.exe',
     'E:\\springboot-idea\\JavaScript\\web\\nodejs\\processDemo.js' ],
  execArgv: [],
  env:
   { ALLUSERSPROFILE: 'C:\\ProgramData',
     APPDATA: 'C:\\Users\\19616\\AppData\\Roaming',
     APR_ICONV_PATH: 'C:\\soft\\iconv',
     CATALINA_HOME: 'F:\\apache-tomcat-8.5.45\\apache-tomcat-8.5.45',
     CLASSPATH:
      '.;C:\\Program Files\\Java\\jdk1.8.0_31\\lib\\dt.jar;C:\\Program Files\\Java\\jdk1.8.0_31\\lib\\tools.jar',
     COLORTERM: 'true',
     CommonProgramFiles: 'C:\\Program Files\\Common Files',
     'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
     CommonProgramW6432: 'C:\\Program Files\\Common Files',
     COMPUTERNAME: 'DESKTOP-OES1NCR',
     ComSpec: 'C:\\Windows\\system32\\cmd.exe',
     DEBUG_COLORS: 'true',
     DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
     ELECTRON_NO_ATTACH_CONSOLE: 'true',
     FORCE_COLOR: 'true',
     HOMEDRIVE: 'C:',
     HOMEPATH: '\\Users\\19616',
     JAVA_HOME: 'C:\\Program Files\\Java\\jdk1.8.0_31',
     LANG: 'zh_CN.GBK',
     LOCALAPPDATA: 'C:\\Users\\19616\\AppData\\Local',
     LOGONSERVER: '\\\\DESKTOP-OES1NCR',
     MAVEN_HOME: 'C:\\soft\\apache-maven-3.6.1-bin\\apache-maven-3.6.1',
     MOCHA_COLORS: '1',
     MOZ_PLUGIN_PATH: 'F:\\Foxit Reader\\plugins\\',
     NLS_LANG: 'AMERICAN_AMERICA.ZHS16GBK',
     npm_config_color: 'always',
     NUMBER_OF_PROCESSORS: '4',
     OneDrive: 'C:\\Users\\19616\\OneDrive',
     OneDriveConsumer: 'C:\\Users\\19616\\OneDrive',
     ORACLE_HOME: 'C:\\soft\\oracle_instantclient_11\\oracle_instantclient_11',
     OS: 'Windows_NT',
     Path:
      'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\VanDyke Software\\Clients\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\soft\\Git\\cmd;C:\\Program Files\\Java\\jdk1.8.0_31\\bin;C:\\Program Files\\Java\\jdk1.8.0_31\\jre\\bin;C:\\soft\\bin;C:\\soft\\apache-maven-3.6.1-bin\\apache-maven-3.6.1\\bin;F:\\apache-tomcat-8.5.45\\apache-tomcat-8.5.45\\bin;F:\\node\\;C:\\Users\\19616\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\19616\\AppData\\Local\\BypassRuntm;C:\\Users\\19616\\AppData\\Roaming\\npm;F:\\node;C:\\Users\\19616\\AppData\\Roaming\\npm\\typings;C:\\Users\\19616\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\\;',
     PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
     PROCESSOR_ARCHITECTURE: 'AMD64',
     PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
     PROCESSOR_LEVEL: '6',
     PROCESSOR_REVISION: '3c03',
     ProgramData: 'C:\\ProgramData',
     ProgramFiles: 'C:\\Program Files',
     'ProgramFiles(x86)': 'C:\\Program Files (x86)',
     ProgramW6432: 'C:\\Program Files',
     PSModulePath:
      'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
     PUBLIC: 'C:\\Users\\Public',
     SESSIONNAME: 'Console',
     SystemDrive: 'C:',
     SystemRoot: 'C:\\Windows',
     TEMP: 'C:\\Users\\19616\\AppData\\Local\\Temp',
     TMP: 'C:\\Users\\19616\\AppData\\Local\\Temp',
     TNS_ADMIN:
      'C:\\soft\\oracle_instantclient_11\\oracle_instantclient_11\\NETWORK\\ADMIN',
     USERDOMAIN: 'DESKTOP-OES1NCR',
     USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-OES1NCR',
     USERNAME: '19616',
     USERPROFILE: 'C:\\Users\\19616',
     windir: 'C:\\Windows' },
  pid: 6612,
  features:
   { debug: false,
     uv: true,
     ipv6: true,
     tls_alpn: true,
     tls_sni: true,
     tls_ocsp: true,
     tls: true },
  ppid: 42356,
  execPath: 'F:\\node\\node.exe',
  debugPort: 9229,
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
  _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
  abort: [Function: abort],
  chdir: [Function: chdir],
  umask: [Function: umask],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  _kill: [Function: _kill],
  cwd: [Function: cwd],
  dlopen: [Function: dlopen],
  reallyExit: [Function: reallyExit],
  uptime: [Function: uptime],
  _rawDebug: [Function],
  moduleLoadList:
   [ 'Internal Binding module_wrap',
     'Binding contextify',
     'Internal Binding worker',
     'NativeModule events',
     'NativeModule internal/async_hooks',
     'NativeModule internal/errors',
     'Binding uv',
     'Binding buffer',
     'Binding async_wrap',
     'Internal Binding async_wrap',
     'Binding config',
     'Binding icu',
     'NativeModule util',
     'NativeModule internal/util/inspect',
     'Binding util',
     'NativeModule internal/util',
     'Binding constants',
     'Internal Binding types',
     'NativeModule internal/util/types',
     'NativeModule internal/validators',
     'NativeModule internal/encoding',
     'Internal Binding icu',
     'NativeModule buffer',
     'NativeModule internal/buffer',
     'NativeModule internal/process/per_thread',
     'NativeModule internal/process/main_thread_only',
     'NativeModule internal/process/stdio',
     'NativeModule assert',
     'NativeModule internal/assert',
     'NativeModule fs',
     'NativeModule path',
     'NativeModule internal/constants',
     'Binding fs',
     'NativeModule internal/fs/streams',
     'NativeModule internal/fs/utils',
     'NativeModule stream',
     'NativeModule internal/streams/pipeline',
     'NativeModule internal/streams/end-of-stream',
     'NativeModule internal/streams/legacy',
     'NativeModule _stream_readable',
     'NativeModule internal/streams/buffer_list',
     'NativeModule internal/streams/destroy',
     'NativeModule internal/streams/state',
     'NativeModule _stream_writable',
     'NativeModule _stream_duplex',
     'NativeModule _stream_transform',
     'NativeModule _stream_passthrough',
     'NativeModule internal/url',
     'NativeModule internal/querystring',
     'Binding url',
     'NativeModule internal/process/warning',
     'NativeModule internal/process/next_tick',
     'NativeModule internal/process/promises',
     'Internal Binding util',
     'NativeModule internal/fixed_queue',
     'Binding performance',
     'Binding trace_events',
     'NativeModule internal/inspector_async_hook',
     'Binding inspector',
     'NativeModule internal/options',
     'Internal Binding options',
     'NativeModule timers',
     'Binding timer_wrap',
     'NativeModule internal/linkedlist',
     'NativeModule internal/timers',
     'NativeModule console',
     'Binding tty_wrap',
     'Internal Binding tty_wrap',
     'NativeModule net',
     'NativeModule internal/net',
     'Binding stream_wrap',
     'Binding tcp_wrap',
     'Binding pipe_wrap',
     'NativeModule internal/stream_base_commons',
     'Internal Binding stream_wrap',
     'Internal Binding uv',
     'NativeModule internal/modules/cjs/loader',
     'NativeModule vm',
     'NativeModule internal/modules/cjs/helpers',
     'NativeModule url',
     'NativeModule internal/safe_globals',
     'Internal Binding contextify' ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events:
   [Object: null prototype] {
     newListener: [Function],
     removeListener: [Function],
     warning: [Function] },
  _eventsCount: 3,
  _maxListeners: undefined,
  _fatalException: [Function],
  domain: null,
  _exiting: false,
  assert: [Function: deprecated],
  config:
   { target_defaults:
      { cflags: [],
        default_configuration: 'Release',
        defines: [],
        include_dirs: [],
        libraries: [] },
     variables:
      { asan: 0,
        build_v8_with_gn: false,
        coverage: false,
        debug_nghttp2: false,
        enable_lto: false,
        enable_pgo_generate: false,
        enable_pgo_use: false,
        force_dynamic_crt: 0,
        host_arch: 'x64',
        icu_data_in: '..\\..\\deps/icu-small\\source/data/in\\icudt64l.dat',
        icu_endianness: 'l',
        icu_gyp_path: 'tools/icu/icu-generic.gyp',
        icu_locales: 'en,root',
        icu_path: 'deps/icu-small',
        icu_small: true,
        icu_ver_major: '64',
        nasm_version: '2.14',
        node_byteorder: 'little',
        node_debug_lib: false,
        node_enable_d8: false,
        node_enable_v8_vtunejit: false,
        node_install_npm: true,
        node_module_version: 64,
        node_no_browser_globals: false,
        node_prefix: '/usr/local',
        node_release_urlbase: 'https://nodejs.org/download/release/',
        node_shared: false,
        node_shared_cares: false,
        node_shared_http_parser: false,
        node_shared_libuv: false,
        node_shared_nghttp2: false,
        node_shared_openssl: false,
        node_shared_zlib: false,
        node_tag: '',
        node_target_type: 'executable',
        node_use_bundled_v8: true,
        node_use_dtrace: false,
        node_use_etw: true,
        node_use_large_pages: false,
        node_use_openssl: true,
        node_use_pch: false,
        node_use_perfctr: true,
        node_use_v8_platform: true,
        node_with_ltcg: true,
        node_without_node_options: false,
        openssl_fips: '',
        openssl_no_asm: 0,
        shlib_suffix: 'so.64',
        target_arch: 'x64',
        v8_enable_gdbjit: 0,
        v8_enable_i18n_support: 1,
        v8_enable_inspector: 1,
        v8_no_strict_aliasing: 1,
        v8_optimized_debug: 0,
        v8_promise_internal_field_count: 1,
        v8_random_seed: 0,
        v8_trace_maps: 0,
        v8_typed_array_max_size_in_heap: 0,
        v8_use_snapshot: true,
        want_separate_host_toolset: 0 } },
  setUncaughtExceptionCaptureCallback: [Function],
  hasUncaughtExceptionCaptureCallback: [Function],
  emitWarning: [Function],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: _tickCallback],
  stdout: [Getter],
  stderr: [Getter],
  stdin: [Getter],
  openStdin: [Function],
  hrtime: { [Function: hrtime] bigint: [Function] },
  cpuUsage: [Function: cpuUsage],
  memoryUsage: [Function: memoryUsage],
  exit: [Function],
  kill: [Function],
  argv0: 'F:\\node\\node.exe',
  allowedNodeEnvironmentFlags: [Getter/Setter],
  mainModule:
   Module {
     id: '.',
     exports: {},
     parent: null,
     filename:
      'E:\\springboot-idea\\JavaScript\\web\\nodejs\\processDemo.js',
     loaded: false,
     children: [],
     paths:
      [ 'E:\\springboot-idea\\JavaScript\\web\\nodejs\\node_modules',
        'E:\\springboot-idea\\JavaScript\\web\\node_modules',
        'E:\\springboot-idea\\JavaScript\\node_modules',
        'E:\\springboot-idea\\node_modules',
        'E:\\node_modules' ] } }
 */
